Repository lightdash/lightdash, pull requests merged in 2022-04, with the labels that each got.

#1691 feat: confirm user wants to delete chart with linked dashboards
  packages/backend/src/models/DashboardModel/DashboardModel.ts
  packages/backend/src/routers/projectRouter.ts
  packages/backend/src/services/DashboardService/DashboardService.test.ts
  packages/backend/src/services/DashboardService/DashboardService.ts
  packages/common/src/openapi/paths/projectDashboards.json
  packages/common/src/openapibundle.json
  packages/frontend/src/components/Explorer.tsx
  packages/frontend/src/hooks/dashboard/useDashboards.tsx
Labels: QA

#1648 feat: add chart config to update big number label
  packages/backend/src/database/seeds/development/02_saved_queries.ts
  packages/common/src/types/savedCharts.ts
  packages/frontend/src/components/BigNumberConfig/BigNumberConfig.styles.ts
  packages/frontend/src/components/BigNumberConfig/index.tsx
  packages/frontend/src/components/ChartConfigPanel/index.tsx
  packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
  packages/frontend/src/components/Explorer.tsx
  packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
  packages/frontend/src/components/SimpleStatistic/index.tsx
  packages/frontend/src/hooks/useBigNumberConfig.ts
  packages/frontend/src/hooks/useCartesianChartConfig.ts
  packages/frontend/src/hooks/usePlottedData.ts
  packages/frontend/src/utils/bigNumberConfig.ts
Labels: QA

#1723 fix: replace history on enter dashboard edit mode
  packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Labels: QA

#1734 docs: update new features
  docs/docs/guides/assets/add-filter-dashboard.png
  docs/docs/guides/assets/add-filter-results-table.png
  docs/docs/guides/assets/add-filter-sidebar.png
  docs/docs/guides/assets/add-filter.png
  docs/docs/guides/assets/adding-filters-from-toggle-1.png
  docs/docs/guides/assets/changing-default-colours.png
  docs/docs/guides/assets/cross-filtering-dashboard.png
  docs/docs/guides/assets/dashboard-filter-applied.png
  docs/docs/guides/assets/edit-dashboard.png
  docs/docs/guides/assets/edit-or-remove-dashboard-filters.png
  docs/docs/guides/assets/new-filters-dashboard.png
  docs/docs/guides/assets/save-new-filters-dashboard.png
  docs/docs/guides/assets/saved-filters-applied.png
  docs/docs/guides/assets/screenshot-create-project.png
  docs/docs/guides/assets/screenshot-delete-project.png
  docs/docs/guides/assets/screenshot-multiple-values-filter.png
  docs/docs/guides/assets/screenshot-switch-projects.png
  docs/docs/guides/customizing-the-appearance-of-your-project.md
  docs/docs/guides/how-to-create-multiple-projects.md
  docs/docs/guides/limiting-data-using-filters.md
  docs/docs/references/filters.md
Labels: documentation

#1720 feat: duplicate chart endpoint
  packages/backend/src/analytics/LightdashAnalytics.ts
  packages/backend/src/routers/projectRouter.ts
  packages/backend/src/services/SavedChartsService/SavedChartService.ts
  packages/common/src/openapi/paths/projectSavedCharts.json
  packages/common/src/openapibundle.json
Labels: discussion

#1711 fix: fix save changes disabled button for bigint and tables
  packages/frontend/src/components/Explorer.tsx
Labels: QA

#1650 feat: update default chart configs
  packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
  packages/frontend/src/hooks/useCartesianChartConfig.ts
Labels: QA

#1756 docs: adds formatting docs and updates reference docs
  docs/docs/get-started/exploring-data/assets/browse-dashboards.png
  docs/docs/get-started/exploring-data/dashboards.md
  docs/docs/guides/assets/add-more-filters-dashboard.png
  docs/docs/guides/assets/default-colours-in-config.png
  docs/docs/guides/assets/description-on-hover.png
  docs/docs/guides/customizing-the-appearance-of-your-project.md
  docs/docs/guides/formatting-your-fields.md
  docs/docs/guides/how-to-create-multiple-projects.md
  docs/docs/guides/limiting-data-using-filters.md
  docs/docs/references/dimensions.md
  docs/docs/references/metrics.md
  docs/sidebars.js
Labels: documentation

#1755 feat: headway widget
  packages/frontend/src/components/NavBar/HelpMenu/HelpMenu.styles.tsx
  packages/frontend/src/components/NavBar/HelpMenu/index.tsx
  packages/frontend/src/providers/AppProvider.tsx
Labels: QA

#1778 feat: bring consistency around chart ations 2
  packages/frontend/src/components/Explorer.tsx
  packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
  packages/frontend/src/components/SavedDashboards/AddTilesToDashboardModal.tsx
  packages/frontend/src/components/common/ActionCardList/ActionCardList.style.tsx
  packages/frontend/src/components/common/ActionCardList/index.tsx
  packages/frontend/src/components/common/modal/ActionModal.tsx
  packages/frontend/src/components/common/modal/ModalActionButtons.tsx
Labels: QA

#1764 feat: add additionalmetrics to runquery
  packages/backend/src/database/entities/savedCharts.ts
  packages/backend/src/database/migrations/20220413083945_additional_metrics.ts
  packages/backend/src/dbt/translator.ts
  packages/backend/src/exploreCompiler.ts
  packages/backend/src/models/SavedChartModel.ts
  packages/backend/src/queryBuilder.mock.ts
  packages/backend/src/queryBuilder.test.ts
  packages/backend/src/queryBuilder.ts
  packages/backend/src/queryCompiler.mock.ts
  packages/backend/src/queryCompiler.test.ts
  packages/backend/src/queryCompiler.ts
  packages/backend/src/routers/projectRouter.ts
  packages/common/src/index.ts
  packages/common/src/types/dbt.ts
  packages/common/src/types/metricQuery.ts
  packages/frontend/src/hooks/useCompiledSql.tsx
  packages/frontend/src/hooks/useExplorerRoute.ts
  packages/frontend/src/hooks/useQueryResults.tsx
  packages/frontend/src/pages/SavedExplorer.tsx
  packages/frontend/src/providers/ExplorerProvider.tsx
Labels: QA

#1777 feat: navigate to chart when duplicated 2
  packages/frontend/src/components/Explorer.tsx
  packages/frontend/src/components/common/modal/ModalActionButtons.tsx
  packages/frontend/src/hooks/dashboard/useDashboard.tsx
  packages/frontend/src/hooks/useSavedQuery.ts
Labels: QA

#1806 fix: remove overridequeryuuid condition on save changes
  packages/frontend/src/components/Explorer.tsx
Labels: QA

#1790 refactor: remove magic metrics
  packages/backend/src/dbt/translator.mock.ts
  packages/backend/src/dbt/translator.test.ts
  packages/backend/src/dbt/translator.ts
  packages/frontend/src/components/TableTree.tsx
Labels: QA

#1813 fix: make sure window has mounted before initilizing Headway
  packages/frontend/src/components/NavBar/HelpMenu/index.tsx
Labels: bug

#1833 fix: make field search more strict with fuse options
  packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
  packages/frontend/src/components/TableTree.tsx
Labels: bug

#1856 docs: updates bigquery connection docs
  docs/docs/get-started/setup-lightdash/assets/data-location.png
  docs/docs/get-started/setup-lightdash/assets/get-to-projects.png
  docs/docs/get-started/setup-lightdash/assets/project-id-list.png
  docs/docs/get-started/setup-lightdash/connect-project.mdx
Labels: documentation

#1861 docs: updates connection docs
  docs/docs/get-started/setup-lightdash/connect-project.mdx
Labels: documentation

#1862 docs: updates dbt project connection docs
  docs/docs/get-started/setup-lightdash/connect-project.mdx
Labels: documentation

#1890 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: 📖 documentation

#1893 updates data location docs
  docs/docs/get-started/setup-lightdash/connect-project.mdx
Labels: 📖 documentation

#1900 docs: adds dashboard interactivity docs
  docs/docs/guides/assets/cross-filtering-applied.png
  docs/docs/guides/assets/cross-filtering.png
  docs/docs/guides/interactive-dashboards.mdx
  docs/sidebars.js
Labels: 📖 documentation

#1913 fix: table visualization pivot
  packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
Labels: 🐛 bug

#1904 docs: add table calculations docs
  docs/docs/guides/adding-custom-metrics.mdx
  docs/docs/guides/table-calculations/adding-table-calculations.mdx
  docs/docs/guides/table-calculations/assets/add-table-calc-sql.png
  docs/docs/guides/table-calculations/assets/create-new-table-calc.png
  docs/docs/guides/table-calculations/assets/data-in-results-table.png
  docs/docs/guides/table-calculations/assets/edit-delete-table-calc.png
  docs/docs/guides/table-calculations/assets/run-query-to-see-table-calcs.png
  docs/docs/guides/table-calculations/assets/table-calculations-add.png
  docs/docs/guides/table-calculations/table-calculation-sql-templates/assets/percent-change.png
  docs/docs/guides/table-calculations/table-calculation-sql-templates/assets/percent-of-previous.png
  docs/docs/guides/table-calculations/table-calculation-sql-templates/assets/percent-of-total-rounded.png
  docs/docs/guides/table-calculations/table-calculation-sql-templates/assets/percent-of-total.png
  docs/docs/guides/table-calculations/table-calculation-sql-templates/assets/rank-in-column.png
  docs/docs/guides/table-calculations/table-calculation-sql-templates/assets/running-total.png
  docs/docs/guides/table-calculations/table-calculation-sql-templates/percent-change-from-previous.mdx
  docs/docs/guides/table-calculations/table-calculation-sql-templates/percent-of-previous-value.mdx
  docs/docs/guides/table-calculations/table-calculation-sql-templates/percent-of-total-column.mdx
  docs/docs/guides/table-calculations/table-calculation-sql-templates/rank-in-column.mdx
  docs/docs/guides/table-calculations/table-calculation-sql-templates/running-total.mdx
  docs/sidebars.js
Labels: 📖 documentation

#1881 feat: cache warehouse
  packages/backend/src/@types/knex-tables.d.ts
  packages/backend/src/database/entities/projects.ts
  packages/backend/src/database/migrations/20220425072608_cache_warehouse.ts
  packages/backend/src/models/ProjectModel/ProjectModel.ts
  packages/backend/src/projectAdapters/dbtAzureDevOpsProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtBaseProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtBitBucketProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtCloudIdeProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtGitProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtGithubProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtGitlabProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtLocalCredentialsProjectAdapter.ts
  packages/backend/src/projectAdapters/dbtLocalProjectAdapter.ts
  packages/backend/src/projectAdapters/projectAdapter.ts
  packages/backend/src/services/ProjectService/ProjectService.ts
  packages/backend/src/types.ts
Labels: 💬 discussion

#1921 feat: remove custom metric option
  packages/frontend/src/components/TableTree.tsx
  packages/frontend/src/providers/ExplorerProvider.tsx
  packages/frontend/src/providers/TrackingProvider.tsx
  packages/frontend/src/types/Events.ts
Labels: 🖥 frontend
