Repository lightdash/lightdash, pull requests merged in 2022-12, with the labels that each got.

#3888 docs: update signup links
  README.md
  docs/docs/get-started/setup-lightdash/install-lightdash.mdx
Labels: 📖 documentation

#3890 docs: add dashboard filters
  docs/docs/guides/assets/filter-tile-adjust.jpg
  docs/docs/guides/assets/filter-tiles-tab.jpg
  docs/docs/guides/limiting-data-using-filters.mdx
Labels: 📖 documentation

#3903 chore: watch for common/warehouses. use ts-node-dev for backend
  package.json
  packages/backend/package.json
  packages/common/package.json
  packages/warehouses/package.json
  yarn.lock
Labels: 👩‍💻 devx, tech-debt

#3917 docs: add dev set up command to fix error when running build script
  .github/CONTRIBUTING.md
Labels: 🐛 bug, 🏄 onboarding

#3997 docs: adds reference line docs
  docs/docs/guides/assets/add-reference-line.png
  docs/docs/guides/assets/reference-line-config.png
  docs/docs/guides/visualizing-your-results.mdx
Labels: 📖 documentation

#4036 docs: add drill down docs
  docs/docs/get-started/setup-a-github-project.md
  docs/docs/guides/assets/drill-by-action-menu.png
  docs/docs/guides/assets/drill-by-modal.png
  docs/docs/guides/assets/drill-by-source-example.png
  docs/docs/guides/exploring-your-content.mdx
  docs/docs/guides/interactive-dashboards.mdx
Labels: 📖 documentation
