Repository lightdash/lightdash, pull requests merged in 2022-01, with the labels that each got.

#1071 Add demo login details to run instructions
  .github/CONTRIBUTING.md
Labels: documentation

#1102 docs: make a note of the memory docker requires to run the container
  .github/CONTRIBUTING.md
Labels: documentation

#1117 chore: configure dev proxy to allow text/html
  packages/frontend/package.json
  packages/frontend/src/setupProxy.js
Labels: devx

#1118 feat: add site url configuration
  docker/.env
  dockerfile-prs
  packages/backend/src/config/parseConfig.ts
  packages/backend/src/health.ts
  packages/backend/src/models/InviteLinkModel.ts
  packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
  packages/backend/src/services/UserService.ts
  packages/common/src/index.ts
  packages/common/src/openapi/schemas/InviteLink.json
  packages/common/src/openapibundle.json
  packages/frontend/src/components/UserSettingsModal/InvitesPanel.tsx
  packages/frontend/src/hooks/useInviteLink.tsx
Labels: feature-request, devx

#1110 feat: mobile UI
  packages/frontend/src/App.tsx
  packages/frontend/src/components/Mobile/Mobile.styles.tsx
  packages/frontend/src/components/Mobile/index.tsx
  packages/frontend/src/hooks/useBreakpoint/index.ts
  packages/frontend/src/pages/Welcome.tsx
  packages/frontend/src/svgs/logo-dark.svg
Labels: bug, frontend, ux-day, P3

#1120 feat: capture users job title
  packages/backend/src/analytics/LightdashAnalytics.ts
  packages/backend/src/api/apiV1.ts
  packages/backend/src/api/userRouter.ts
  packages/backend/src/services/UserService.ts
  packages/common/src/index.ts
  packages/e2e/cypress/integration/settings/invites.spec.ts
  packages/frontend/src/components/CreateUserForm.tsx
Labels: feature-request

#1142 fix: adds responsiveness to the dashboard charts on screen resize
  packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
  packages/frontend/src/components/Explorer.tsx
  packages/frontend/src/components/SimpleChart/index.tsx
Labels: ux-day

#1158 fix(#1106): update copy on home page primary action
  packages/frontend/src/pages/Home.tsx
Labels: frontend, ux-day

#1157 feat: customise pg pool size
  packages/backend/setupJest.ts
  packages/backend/src/config/parseConfig.test.ts
  packages/backend/src/config/parseConfig.ts
  packages/backend/src/database/knexfile.ts
  packages/backend/src/models/ProjectModel/ProjectModel.mock.ts
Labels: feature-request, backend

#1161 feat: add tooltip with description to column title
  packages/frontend/src/components/ResultsTable/ResultsTable.tsx
  packages/frontend/src/hooks/useColumns.tsx
  packages/frontend/src/types/react-table-config.d.ts
Labels: frontend, good first issue, ux

#1202 feat: search table by name and show unlisted tables
  packages/frontend/src/components/ExploreSideBar.tsx
  packages/frontend/src/components/Explorer/ExplorePanel/ExplorePanel.styles.ts
  packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
  packages/frontend/src/components/Explorer/ExploreSideBar/ExploreSideBar.styles.ts
  packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
  packages/frontend/src/hooks/useExplores.tsx
  packages/frontend/src/pages/Explorer.tsx
  packages/frontend/src/pages/SavedExplorer.tsx
Labels: feature-request

#1253 feat: support no-verify for postgres connections
  packages/backend/src/services/warehouseClients/RedshiftWarehouseClient.ts
  packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
  packages/frontend/src/components/ProjectConnection/WarehouseForms/RedshiftForm.tsx
Labels: feature-request, backend

#1261 chore: set LIGHTDASH_LOG_LEVEL=debug on development environments
  .env.fast-install
  docker-compose.yml
  docker/.env
  docker/docker-compose.dev.yml
Labels: devx
