Repository lightdash/lightdash, pull requests merged in 2022-08, with the labels that each got.

#2830 docs: Update groups
  docs/docs/guides/formatting-your-fields.mdx
Labels: 📖 documentation

#2835 docs: update spaces
  docs/docs/guides/assets/access-spaces.png
  docs/docs/guides/assets/add-modal.png
  docs/docs/guides/assets/add-within-space.png
  docs/docs/guides/assets/move-between-space.png
  docs/docs/guides/assets/rename-delete-space.png
  docs/docs/guides/assets/spaces.png
  docs/docs/guides/spaces.mdx
  docs/docs/intro.md
  docs/sidebars.js
Labels: 📖 documentation

#2869 docs: update running total
  docs/docs/guides/table-calculations/table-calculation-sql-templates/running-total.mdx
Labels: 📖 documentation

#2870 docs: fix dbt cloud in connection docs
  docs/docs/get-started/setup-lightdash/connect-project.mdx
Labels: 📖 documentation

#2894 feat: user can login to the cli with a token
  docs/docs/get-started/setup-lightdash/add-metrics.mdx
  docs/docs/guides/cli/how-to-install-the-lightdash-cli.mdx
  docs/docs/guides/how-to-create-dimensions.md
  packages/cli/src/handlers/login.ts
  packages/cli/src/index.ts
Labels: ✨ feature-request, 🎮 CLI

#2926 docs: adds personal access token image
  docs/docs/guides/cli/assets/personal-access-token.png
  docs/docs/guides/cli/how-to-install-the-lightdash-cli.mdx
Labels: 📖 documentation

#2923 feat: read and create users/spaces/dashboards/charts with personal access token
  packages/backend/src/routers/dashboardRouter.ts
  packages/backend/src/routers/inviteLinksRouter.ts
  packages/backend/src/routers/organizationRouter.ts
  packages/backend/src/routers/projectRouter.ts
  packages/backend/src/routers/savedChartRouter.ts
Labels: ✨ feature-request, ⚙️ backend

#2941 chore: refactor pivot data logic
  packages/frontend/src/components/ChartConfigPanel/index.tsx
  packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
  packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
  packages/frontend/src/hooks/echarts/useEcharts.ts
  packages/frontend/src/hooks/plottedData/usePlottedData.mock.ts
  packages/frontend/src/hooks/plottedData/usePlottedData.test.ts
  packages/frontend/src/hooks/plottedData/usePlottedData.ts
  packages/frontend/src/hooks/usePlottedData.ts
Labels: 🖥 frontend, tech-debt

#2958 fix: performance when ordering columns
  packages/frontend/src/components/common/Table/ScrollableTable/HeaderDnD.tsx
  packages/frontend/src/components/common/Table/TableProvider.tsx
  packages/frontend/src/providers/ExplorerProvider.tsx
Labels: 🐛 bug, 🖥 frontend

#3023 docs: adds underlying data docs
  docs/docs/get-started/exploring-data/assets/view-underlying-data-click.png
  docs/docs/get-started/exploring-data/assets/view-underlying-data-table.png
  docs/docs/get-started/exploring-data/using-explores.mdx
  docs/docs/guides/assets/underlying-data-click-chart.png
  docs/docs/guides/assets/view-underlying-data-table-chart.png
  docs/docs/guides/interactive-dashboards.mdx
  docs/docs/guides/limiting-data-using-filters.md
Labels: 📖 documentation

#3049 docs: update dimensions docs
  docs/docs/get-started/exploring-data/assets/explore-screenshot.jpg
  docs/docs/get-started/exploring-data/assets/explore_screenshot.png
  docs/docs/get-started/exploring-data/assets/results-table.png
  docs/docs/get-started/exploring-data/assets/results_screenshot.png
  docs/docs/get-started/exploring-data/assets/save-chart.jpg
  docs/docs/get-started/exploring-data/assets/save_chart_action.png
  docs/docs/get-started/exploring-data/assets/view-underlying-data-click.png
  docs/docs/get-started/exploring-data/assets/view-underlying-data-table.png
  docs/docs/get-started/exploring-data/assets/view-underlying-data.jpg
  docs/docs/get-started/exploring-data/sharing-insights.mdx
  docs/docs/get-started/exploring-data/using-explores.mdx
  docs/docs/guides/adding-tables-to-lightdash.mdx
  docs/docs/guides/assets/example-table.jpg
  docs/docs/guides/assets/example_table.png
  docs/docs/guides/assets/overview-tables.png
  docs/docs/guides/assets/project-management.png
  docs/docs/guides/assets/tables-configuration.jpg
  docs/docs/guides/assets/tables-configuration.png
  docs/docs/guides/assets/tables-view.jpg
  docs/docs/guides/assets/tables-view.png
  docs/docs/guides/cli/cli-authentication.mdx
  docs/docs/guides/cli/how-to-install-the-lightdash-cli.mdx
  docs/docs/guides/cli/how-to-use-lightdash-preview.mdx
  docs/sidebars.js
  packages/cli/src/index.ts
Labels: 📖 documentation

#3046 feat: result table header styles
  packages/e2e/cypress/e2e/explore.cy.ts
  packages/frontend/src/components/Explorer/VisualizationCardOptions/VisualizationCardOptions.style.tsx
  packages/frontend/src/components/Explorer/VisualizationCardOptions/index.tsx
  packages/frontend/src/components/LightdashVisualization/index.tsx
  packages/frontend/src/components/UnderlyingData/UnderlyingDataResultsTable.tsx
  packages/frontend/src/components/common/Table/Table.styles.ts
  packages/frontend/src/hooks/tableVisualization/getDataAndColumns.ts
  packages/frontend/src/hooks/tableVisualization/getDataAndColumns.tsx
  packages/frontend/src/hooks/tableVisualization/getPivotDataAndColumns.ts
  packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
  packages/frontend/src/hooks/useColumns.tsx
Labels: 🖥 frontend

#3058 docs: update dimension docs
  README.md
  docs/docs/get-started/exploring-data/assets/export-chart.jpg
  docs/docs/get-started/exploring-data/assets/export_csv_action.png
  docs/docs/get-started/exploring-data/assets/export_image_action.png
  docs/docs/get-started/exploring-data/assets/select-table.jpg
  docs/docs/get-started/exploring-data/assets/view_charts_action.png
  docs/docs/get-started/exploring-data/intro.mdx
  docs/docs/get-started/exploring-data/sharing-insights.mdx
  docs/docs/get-started/exploring-data/using-explores.mdx
  docs/docs/get-started/setup-lightdash/add-metrics.mdx
  docs/docs/get-started/setup-lightdash/assets/data-question.jpg
  docs/docs/get-started/setup-lightdash/assets/data-question.svg
  docs/docs/get-started/setup-lightdash/intro-metrics-dimensions.mdx
  docs/docs/get-started/setup-lightdash/intro.mdx
  docs/docs/guides/adding-tables-to-lightdash.mdx
  docs/docs/guides/assets/add-new-dimension-overview.png
  docs/docs/guides/assets/custom-metric-added.jpg
  docs/docs/guides/assets/custom-metric-added.png
  docs/docs/guides/assets/dimensions-in-explore-view.png
  docs/docs/guides/assets/dimensions-in-the-explore-view.jpg
  docs/docs/guides/assets/explore-from-here.jpg
  docs/docs/guides/assets/metrics-explore-view.jpg
  docs/docs/guides/assets/metrics-in-explore-view.png
  docs/docs/guides/assets/select-table.jpg
  docs/docs/guides/assets/underlying-chart-data.jpg
  docs/docs/guides/assets/underlying-data-click-chart.png
  docs/docs/guides/assets/underlying-data.jpg
  docs/docs/guides/assets/view-underlying-data-table-chart.png
  docs/docs/guides/assets/view-underlying-data.jpg
  docs/docs/guides/exploring-your-content.mdx
  docs/docs/guides/formatting-your-fields.mdx
  docs/docs/guides/how-to-create-dimensions.md
  docs/docs/guides/how-to-create-dimensions.mdx
  docs/docs/guides/how-to-create-metrics.mdx
  docs/docs/guides/interactive-dashboards.mdx
  docs/docs/intro.md
  docs/docs/references/dimensions.md
  docs/sidebars.js
  packages/frontend/src/components/ExploreMenuItem.tsx
  packages/frontend/src/components/Explorer/ExploreTree/TableTree/TableTreeSections.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectionOptions.tsx
Labels: 📖 documentation

#3068 docs: update metrics to include reference sheet
  docs/docs/guides/how-to-create-metrics.mdx
Labels: 📖 documentation

#3069 fix: update docs links
  packages/cli/src/index.ts
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectionOptions.tsx
  packages/frontend/src/components/ProjectConnection/index.tsx
Labels: 📖 documentation

#3074 docs: update cli token docs
  docs/docs/guides/cli/cli-authentication.mdx
Labels: 📖 documentation

#3090 docs: fixes doc link for metrics
  docs/docs/guides/how-to-create-metrics.mdx
Labels: 📖 documentation

#3095 chore: add missing keys / migrate MenuItem deprecations / menu appearance
  packages/frontend/src/components/DashboardFilter/FilterSearch/FilterSearch.styles.tsx
  packages/frontend/src/components/DashboardTiles/AddTileButton.tsx
  packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
  packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
  packages/frontend/src/components/ExploreMenuItem.tsx
  packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
  packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
  packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
  packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
  packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowserMenu.tsx
  packages/frontend/src/components/Explorer/SpaceBrowser/index.tsx
  packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
  packages/frontend/src/components/NavBar/BrowseMenu/index.tsx
  packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
  packages/frontend/src/components/NavBar/GlobalSearch/index.tsx
  packages/frontend/src/components/NavBar/NavBar.styles.tsx
  packages/frontend/src/components/NavBar/index.tsx
  packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx
  packages/frontend/src/components/ReactHookForm/MultiSelect.tsx
  packages/frontend/src/components/SavedQueries/SavedQueriesMenu.tsx
  packages/frontend/src/components/SimpleStatistic/BigNumberContextMenu.tsx
  packages/frontend/src/components/TableCalculationHeaderButton.tsx
  packages/frontend/src/components/UnderlyingData/UnderlyingDataModal.tsx
  packages/frontend/src/components/common/Filters/FilterInputs/StringAutoComplete.tsx
  packages/frontend/src/components/common/Filters/FilterInputs/UnitOfTimeAutoComplete.tsx
  packages/frontend/src/components/common/RouterMenuItem.tsx
  packages/frontend/src/components/common/SideBarLoadingState.tsx
  packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
  packages/frontend/src/components/common/modal/ModalActionButtons.tsx
Labels: 👩‍💻 devx

#3047 feat: column header interactivity
  packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
  packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
  packages/frontend/src/components/TableCalculationHeaderButton.tsx
  packages/frontend/src/components/common/Table/ScrollableTable/TableHeader.tsx
  packages/frontend/src/components/common/Table/Table.styles.ts
  packages/frontend/src/components/common/Table/TableProvider.tsx
Labels: 🖥 frontend

#3119 docs: update roles.md
  docs/docs/references/roles.md
Labels: 📖 documentation

#3091 feat: remove table information dropdown
  packages/backend/src/services/ProjectService/ProjectService.mock.ts
  packages/backend/src/services/ProjectService/ProjectService.ts
  packages/common/src/types/explore.ts
  packages/frontend/src/components/ExploreMenuItem/index.tsx
  packages/frontend/src/components/Explorer/ExplorePanel/ExplorePanel.styles.ts
  packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
  packages/frontend/src/components/Explorer/ExploreSideBar/ExploreSideBar.styles.ts
  packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
  packages/frontend/src/components/Explorer/ExploreTree/TableTree/CollapsibleTableTree.tsx
  packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeSingleNode.tsx
  packages/frontend/src/components/TableInfo/Lineage.tsx
  packages/frontend/src/components/TableInfo/index.tsx
  packages/frontend/src/pages/SavedExplorer.tsx
  packages/frontend/src/providers/TrackingProvider.tsx
  packages/frontend/src/types/Events.ts
Labels: 🖥 frontend

#3108 chore: refactor ExplorerProvider to use context selector
  packages/frontend/package.json
  packages/frontend/src/components/ExploreFromHereButton/index.tsx
  packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
  packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
  packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/CustomMetricButtons.tsx
  packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/FieldButtons.tsx
  packages/frontend/src/components/Explorer/ExplorerHeader/index.tsx
  packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
  packages/frontend/src/components/Explorer/ResultsCard/ColumnHeaderContextMenu.tsx
  packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
  packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
  packages/frontend/src/components/Explorer/SaveChartButton/index.tsx
  packages/frontend/src/components/Explorer/SavedChartsHeader/index.tsx
  packages/frontend/src/components/Explorer/SqlCard/SqlCard.tsx
  packages/frontend/src/components/Explorer/VisualizationCard/SeriesContextMenu.tsx
  packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
  packages/frontend/src/components/Explorer/index.tsx
  packages/frontend/src/components/NavBar/ExploreMenu/index.tsx
  packages/frontend/src/components/NavBar/index.tsx
  packages/frontend/src/components/RefreshButton.tsx
  packages/frontend/src/components/TableCalculationModels/CreateTableCalculationModal.tsx
  packages/frontend/src/components/TableCalculationModels/DeleteTableCalculationModal.tsx
  packages/frontend/src/components/TableCalculationModels/TableCalculationModal.tsx
  packages/frontend/src/components/TableCalculationModels/UpdateTableCalculationModal.tsx
  packages/frontend/src/hooks/useColumns.tsx
  packages/frontend/src/hooks/useCompiledSql.tsx
  packages/frontend/src/hooks/useExplorerAceEditorCompleter.tsx
  packages/frontend/src/hooks/useExplorerRoute.ts
  packages/frontend/src/hooks/useFilters.ts
  packages/frontend/src/pages/Explorer.tsx
  packages/frontend/src/providers/ExplorerProvider.tsx
  yarn.lock
Labels: 🖥 frontend, tech-debt
