Repository lightdash/lightdash, pull requests merged in 2022-05, with the labels that each got.

#1971 fix: Redirect user to the home pack when a chart is deleted from the …
  packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
Labels: 🐛 bug

#1974 docs: updates custom metrics docs
  docs/docs/guides/adding-custom-metrics.mdx
  docs/docs/guides/assets/custom-metric-added.png
  docs/docs/guides/assets/delete-custom-metric.png
  docs/docs/guides/assets/three-dot-option.png
Labels: 📖 documentation

#1967 fix: update delete modal action to be generic and delete dashboards a…
  packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
  packages/frontend/src/components/SavedDashboards/DeleteDashboardModal.tsx
  packages/frontend/src/components/common/ActionCardList/index.tsx
  packages/frontend/src/components/common/modal/DeleteActionModal.tsx
  packages/frontend/src/hooks/dashboard/useDashboards.tsx
Labels: 🐛 bug

#1998 chore: remove redundant property from explorer context
  packages/frontend/src/hooks/useExplorerRoute.ts
  packages/frontend/src/pages/SavedExplorer.tsx
  packages/frontend/src/providers/ExplorerProvider.tsx
Labels: 🖥 frontend, tech-debt

#1975 feat: add message and button to create new charts when none are saved
  packages/frontend/src/components/DashboardTiles/EmptyStateNoTiles/index.tsx
  packages/frontend/src/components/Home/LatestSavedCharts/index.tsx
  packages/frontend/src/components/SavedQueries/EmptySavedChartsState/EmptySavedChartsState.styles.tsx
  packages/frontend/src/components/SavedQueries/EmptySavedChartsState/index.tsx
  packages/frontend/src/components/common/ActionCardList/index.tsx
  packages/frontend/src/pages/Dashboard.tsx
Labels: 🐛 bug

#1991 style: update max height of sql input on full screen
  packages/frontend/src/components/TableCalculationModels/TableCalculationModal.styles.ts
  packages/frontend/src/components/TableCalculationModels/TableCalculationModal.tsx
Labels: 🐛 bug

#2001 fix: remove hello placeholders
  packages/frontend/src/components/Explorer/ExplorePanel/index.tsx
  packages/frontend/src/components/Explorer/ExploreSideBar/index.tsx
  packages/frontend/src/components/common/SideBarLoadingState.tsx
Labels: 🐛 bug

#2003 chore: refactor visualization provider to handle initial values
  packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
  packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
  packages/frontend/src/components/LightdashVisualization/VisualizationProvider.tsx
  packages/frontend/src/hooks/useCartesianChartConfig.ts
  packages/frontend/src/hooks/usePivotDimensions.ts
Labels: 🖥 frontend, tech-debt

#2006 docs: fixes snowflake in threads + updates image
  docs/docs/get-started/setup-lightdash/assets/snowflake-account-url.png
  docs/docs/get-started/setup-lightdash/connect-project.mdx
Labels: 📖 documentation

#2046 fix: use custom sql for date truncate fields
  packages/backend/src/dbt/translator.ts
Labels: 🐛 bug, ⚙️ backend

#2047 chore: remove cell formatting
  packages/frontend/src/hooks/useColumns.tsx
  packages/frontend/src/utils/resultFormatter.tsx
Labels: 🖥 frontend, tech-debt

#2057 fix: regex lookahead
  packages/backend/src/dbt/translator.mock.ts
  packages/common/src/types/metricQuery.ts
Labels: 🐛 bug, 🖥 frontend

#2061 fix: check null
  packages/frontend/src/utils/tableData.ts
Labels: 🐛 bug, 🖥 frontend

#2050 chore: refactor chart pivot value formatting
  packages/backend/src/services/ProjectService/ProjectService.mock.ts
  packages/backend/src/services/ProjectService/ProjectService.test.ts
  packages/common/src/utils/formatting.ts
  packages/frontend/src/components/ChartConfigPanel/Series/GroupedSeriesConfiguration.tsx
  packages/frontend/src/hooks/useEcharts.ts
  packages/frontend/src/utils/resultFormatter.tsx
Labels: 🖥 frontend, tech-debt

#2067 fix: format table calculation values
  packages/common/src/index.ts
  packages/frontend/src/hooks/useColumns.tsx
Labels: 🐛 bug, 🖥 frontend

#2080 docs: updates refresh dbt docs
  docs/docs/references/syncing_your_dbt_changes.md
Labels: 📖 documentation

#2079 fix: format table calculation numbers with commas
  packages/backend/src/services/ProjectService/ProjectService.ts
  packages/common/src/index.ts
  packages/common/src/utils/formatting.ts
  packages/frontend/src/components/SimpleTable/index.tsx
  packages/frontend/src/hooks/useEcharts.ts
Labels: 🐛 bug, 🖥 frontend

#2054 chore: test common package
  .github/workflows/test-and-build.yml
  package.json
  packages/backend/src/services/ProjectService/ProjectService.mock.ts
  packages/backend/src/services/ProjectService/ProjectService.test.ts
  packages/common/package.json
  packages/common/src/index.mock.ts
  packages/common/src/index.test.ts
  yarn.lock
Labels: tech-debt

#2097 fix: updates default colours to be colourblind friendly
  packages/common/src/types/savedCharts.ts
Labels: 🖥 frontend

#2105 fix: fixes typo in sidebar
  packages/frontend/src/components/TableTree.tsx
Labels: 🖥 frontend

#2109 fix: rounding numbers with 4 or more digits
  packages/common/src/index.test.ts
  packages/common/src/utils/formatting.ts
Labels: 🐛 bug, ⚙️ backend

#2112 fix: edit chart url
  packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Labels: 🐛 bug, 🖥 frontend

#2118 docs: adds dimensions and metrics docs
  docs/docs/get-started/exploring-data/dashboards.md
  docs/docs/get-started/exploring-data/using-explores.md
  docs/docs/get-started/setup-lightdash/add-metrics.mdx
  docs/docs/guides/adding-custom-metrics.mdx
  docs/docs/guides/adding-tables-to-lightdash.mdx
  docs/docs/guides/assets/dimensions-in-explore-view.png
  docs/docs/guides/assets/metrics-in-explore-view.png
  docs/docs/guides/how-to-create-dimensions.md
  docs/docs/guides/how-to-create-metrics.md
  docs/docs/guides/how-to-create-metrics.mdx
  docs/docs/guides/how-to-join-tables.md
  docs/docs/references/assets/screenshot-refresh-dbt.png
  docs/docs/references/dimensions.md
  docs/docs/references/metrics.md
  docs/docs/references/syncing_your_dbt_changes.md
  docs/sidebars.js
Labels: 📖 documentation

#2139 docs: change intro doc
  docs/docs/intro.md
Labels: 📖 documentation

#2171 docs: changes column chart to bar chart
  docs/docs/guides/visualizing-your-results.mdx
Labels: 📖 documentation

#2173 docs: updates project connection dbt cloud
  docs/docs/get-started/setup-lightdash/connect-project.mdx
Labels: 📖 documentation

#2267 feat: email invites
  packages/backend/package.json
  packages/backend/src/clients/EmailClient/EmailClient.ts
  packages/backend/src/clients/EmailClient/templates/invite.html
  packages/backend/src/clients/EmailClient/templates/recoverPassword.html
  packages/backend/src/services/UserService.ts
  packages/frontend/src/components/UserSettingsModal/InvitesPanel/InvitesPanel.styles.ts
  packages/frontend/src/components/UserSettingsModal/InvitesPanel/index.tsx
  packages/frontend/src/components/UserSettingsModal/UserManagementPanel/UserManagementPanel.styles.ts
  packages/frontend/src/components/UserSettingsModal/UserManagementPanel/index.tsx
  yarn.lock
Labels: ✨ feature-request, 🖥 frontend, ⚙️ backend
