Repository lightdash/lightdash, pull requests merged in 2023-07, with the labels that each got.

#6136 chore: add mantine import counter
  scripts/count-blueprint-imports.ts
Labels: 👩‍💻 devx

#6120 chore: run cypress tests in parallel
  .github/workflows/e2e-tests.yml
  .github/workflows/manual-trigger-e2e-tests.yml
  .github/workflows/timezone-tests.yml
  packages/e2e/cypress.config.ts
  packages/e2e/cypress/e2e/globalSearch.cy.ts
  packages/e2e/package.json
  yarn.lock
Labels: 👩‍💻 devx

#6143 chore: skip blueprint action for external PRs
  .github/workflows/count-blueprint.yml
Labels: 👩‍💻 devx

#6172 docs: Update filters.md
  docs/docs/references/filters.md
Labels: 📖 documentation

#6184 docs: add query tags, pie chart and default project docs
  docs/docs/guides/assets/pie-chart-display.png
  docs/docs/guides/assets/pie-chart-layout.png
  docs/docs/guides/assets/pie-chart-series.png
  docs/docs/guides/assets/pie-chart.png
  docs/docs/guides/visualizing-your-results.mdx
  docs/docs/references/usage-analytics.mdx
  docs/docs/snippets/allowed-email-domains.mdx
  docs/docs/snippets/assets/project-access.png
Labels: 📖 documentation

#6423 docs: add colour range docs
  docs/docs/guides/assets/color-ranges-example.jpg
  docs/docs/guides/assets/columns-rows-metrics-example.jpg
  docs/docs/guides/assets/conditional-formatting-rule.png
  docs/docs/guides/assets/conditional-formatting.png
  docs/docs/guides/assets/table-chart.png
  docs/docs/guides/visualizing-your-results.mdx
Labels: 📖 documentation

#6448 feat: identify charts that belong to a dashboard
  packages/backend/src/models/DashboardModel/DashboardModel.ts
  packages/backend/src/models/SavedChartModel.ts
  packages/backend/src/services/ValidationService/ValidationService.mock.ts
  packages/common/src/types/dashboard.ts
  packages/common/src/types/savedCharts.ts
  packages/e2e/cypress/e2e/api/dashboard.cy.ts
Labels: ⚙️ backend

#6473 chore: add `concurrently` to improve dev step and introduce `npm-run-all2`
  package.json
  yarn.lock
Labels: 👩‍💻 devx

#6540 feat: onboarding in mantine
  packages/e2e/cypress/e2e/createProjects.cy.ts
  packages/frontend/package.json
  packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/ProjectAccessCreation.ts
  packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/Assets/trino.svg
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/ConnectManuallyStep1.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/ConnectManuallyStep2.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/index.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectSuccess.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectTitle.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/InviteExpertFooter.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ProjectConnectFlow.styles.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/SelectConnectMethod.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/SelectWarehouse.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/UnsupportedWarehouse.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/common/CodeBlock.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/common/OnboardingButton.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/common/OnboardingTitle.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/common/OnboardingWrapper.tsx
  packages/frontend/src/components/ProjectConnection/ProjectFormProvider.tsx
  packages/frontend/src/components/ProjectConnection/index.tsx
  packages/frontend/src/components/RegisterForms/ProjectConnectFlow.styles.tsx
  packages/frontend/src/pages/CreateProject.styles.tsx
  packages/frontend/src/pages/CreateProject.tsx
  packages/frontend/src/pages/VerifyEmail.tsx
  yarn.lock
Labels: ⚡️ LightSmash Day

#6558 docs: fix lowercase broken link in metric docs
  docs/docs/references/metrics.mdx
Labels: 📖 documentation
