Repository lightdash/lightdash, pull requests merged in 2023-08, with the labels that each got.

#6609 feat: filters year and monthyear pickers in mantine
  packages/e2e/cypress/e2e/dates.cy.ts
  packages/frontend/package.json
  packages/frontend/src/components/common/MonthAndYearInput.tsx
  packages/frontend/src/components/common/YearInput.tsx
  yarn.lock
Labels: 🔷 Blueprint

#6661 chore: delete unused images in docs
  docs/docs/get-started/assets/dbt-cloud-account-project.png
  docs/docs/get-started/assets/dbt-cloud-develop.png
  docs/docs/get-started/assets/dbt-cloud-env-details.png
  docs/docs/get-started/assets/dbt-cloud-env-select.png
  docs/docs/get-started/assets/dbt-cloud-sidebar.png
  docs/docs/get-started/assets/heroku-add-secrets-1.png
  docs/docs/get-started/assets/heroku-add-secrets-2.png
  docs/docs/get-started/assets/heroku-envvars.png
  docs/docs/get-started/assets/heroku-github-envvar.png
  docs/docs/get-started/assets/heroku-open-app.png
  docs/docs/get-started/assets/heroku-success-manage.png
  docs/docs/get-started/assets/heroku-success.png
  docs/docs/get-started/exploring-data/assets/dashboard_screenshot.png
  docs/docs/get-started/exploring-data/assets/tutorial_sharing_insights.png
  docs/docs/get-started/setup-lightdash/assets/explore-tables.png
  docs/docs/get-started/setup-lightdash/assets/project-management.png
  docs/docs/get-started/setup-lightdash/assets/show-hidden-tables.png
  docs/docs/get-started/setup-lightdash/assets/tutorial_adding_metrics.png
  docs/docs/guides/assets/explore-tables.png
  docs/docs/guides/assets/save-new-filters-dashboard.png
  docs/docs/guides/assets/saved-filters-applied.png
  docs/docs/guides/assets/screenshot-dimension-info.png
  docs/docs/guides/assets/screenshot-gcp-1.png
  docs/docs/guides/assets/screenshot-gcp-2.png
  docs/docs/guides/assets/screenshot-gcp-3.png
  docs/docs/guides/assets/screenshot-gcp-4.png
  docs/docs/guides/assets/screenshot-gcp-5.png
  docs/docs/guides/assets/screenshot-gcp-6.png
  docs/docs/guides/assets/screenshot-gcp-7.png
  docs/docs/guides/assets/screenshot-gcp-8.png
  docs/docs/guides/assets/screenshot-metrics-view.png
  docs/docs/guides/assets/screenshot-tables-view.png
  docs/docs/guides/assets/view-underlying-data.jpg
  docs/docs/references/assets/screenshot-add-filters.png
Labels: 📖 documentation

#6706 feat: add dashed border to tiles on edit mode
  packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
Labels: ⚡️ LightSmash Day

#6708 feat: make dashboard tiles borders lighter on view mode
  packages/frontend/src/components/DashboardTiles/TileBase/TileBase.styles.tsx
Labels: ⚡️ LightSmash Day

#6710 feat: lighten dashboard-header's shadow
  packages/frontend/src/components/common/Page/PageHeader.tsx
Labels: ⚡️ LightSmash Day

#6803 docs: update dashboard docs
  docs/docs/get-started/exploring-data/all-dashboard-nav.png
  docs/docs/get-started/exploring-data/assets/all-dashboards.jpg
  docs/docs/get-started/exploring-data/assets/create-chart-within-dashboard.jpg
  docs/docs/get-started/exploring-data/assets/create_chart_in_dashboard.png
  docs/docs/get-started/exploring-data/assets/dashboard-add-new-navbar.png
  docs/docs/get-started/exploring-data/assets/dashboard-add-saved-chart.png
  docs/docs/get-started/exploring-data/assets/dashboard-add-tile-center.png
  docs/docs/get-started/exploring-data/assets/move-chart-to-space.jpg
  docs/docs/get-started/exploring-data/dashboard-save-button.png
  docs/docs/get-started/exploring-data/dashboards.md
  docs/docs/get-started/exploring-data/dashboards.mdx
Labels: 📖 documentation

#6822 chore: update docs dependencies
  docs/package.json
  docs/yarn.lock
Labels: tech-debt

#6823 chore: remove deprecated github action
  .github/workflows/cli-tests.yml
  .github/workflows/e2e-tests.yml
Labels: tech-debt

#6830 chore: update create-json github action
  .github/workflows/e2e-tests.yml
Labels: tech-debt

#6875 docs: removes spaces in front of attribute definition
  docs/docs/references/user-attributes.mdx
Labels: 📖 documentation

#6894 feat: move dashboard details to popover
  packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Labels: ⚡️ LightSmash Day

#6896 style: decrease dashboard header height
  packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
  packages/frontend/src/components/common/Page/PageHeader.tsx
Labels: ⚡️ LightSmash Day

#6899 chore: remove small dashboard header icon
  packages/frontend/src/components/common/Dashboard/DashboardHeader.tsx
Labels: ⚡️ LightSmash Day

#6948 docs: add new points for google-sheets-related actions
  docs/docs/references/roles.mdx
Labels: 📖 documentation

#6949 docs: remove google sheets related info from scheduled deliveries
  docs/docs/guides/how-to-create-scheduled-deliveries.mdx
Labels: 📖 documentation
