Repository lightdash/lightdash, pull requests merged in 2023-06, with the labels that each got.

#5766 chore: updates copy on show results total
  packages/frontend/src/components/TableConfigPanel/GeneralSettings.tsx
Labels: 🖥 frontend

#5788 docs: updates reference docs titles
  docs/docs/references/dimensions.mdx
  docs/docs/references/filters.md
  docs/docs/references/joins.md
  docs/docs/references/metrics.mdx
  docs/docs/references/tables.md
  docs/sidebars.js
Labels: 📖 documentation

#5872 docs: updates scheduled deliveries doc to include 3 day expiry
  docs/docs/guides/how-to-create-scheduled-deliveries.mdx
Labels: 📖 documentation

#5992 fix: address issues with fieldId to fieldRef migration file
  packages/backend/src/database/migrations/20230619163121_cached_explores_rename_fieldid_to_fieldref.ts
  packages/common/src/compiler/exploreCompiler.ts
Labels: 🐛 bug, ⚙️ backend

#5997 fix: get correct key for date filters
  packages/common/src/compiler/exploreCompiler.ts
Labels: 🐛 bug, ⚙️ backend

#6059 fix: reduce retry and get org id from param when validating
  packages/backend/src/services/ValidationService/ValidationService.ts
  packages/frontend/src/hooks/validation/useValidation.ts
Labels: 🐛 bug

#6078 docs: Update adding-table-calculations.mdx
  docs/docs/guides/table-calculations/adding-table-calculations.mdx
Labels: 📖 documentation

#6092 fix: preview content where charts have custom metrics
  packages/backend/src/models/ProjectModel/ProjectModel.ts
Labels: 🐛 bug

#6090 fix: dont override custom metric when creating a chart from another c…
  packages/backend/src/@types/knex-tables.d.ts
  packages/backend/src/database/entities/savedCharts.ts
  packages/backend/src/models/SavedChartModel.ts
Labels: 🐛 bug

#6097 fix: add array.at polyfill
  packages/frontend/package.json
  packages/frontend/vite.config.ts
  yarn.lock
Labels: 🐛 bug, 🖥 frontend
