Repository lightdash/lightdash, pull requests merged in 2023-05, with the labels that each got.

#5168 chore: add db queries to pinned api
  packages/backend/src/controllers/pinningController.ts
  packages/backend/src/generated/routes.ts
  packages/backend/src/models/ProjectModel/ProjectModel.ts
  packages/backend/src/models/ResourceViewItemModel.ts
  packages/backend/src/models/models.ts
  packages/backend/src/services/PinningService/PinningService.ts
  packages/backend/src/services/SpaceService/SpaceService.ts
  packages/backend/src/services/services.ts
  packages/common/src/index.ts
  packages/common/src/types/pinning.ts
  packages/common/src/types/projects.ts
  packages/common/src/types/resourceViewItem.ts
  packages/frontend/src/components/PinnedItemsPanel/index.tsx
  packages/frontend/src/hooks/pinning/useChartPinningMutation.ts
  packages/frontend/src/hooks/pinning/useDashboardPinningMutation.ts
  packages/frontend/src/hooks/pinning/usePinnedItems.ts
  packages/frontend/src/hooks/pinning/useSpaceMutation.ts
  packages/frontend/src/pages/Home.tsx
Labels: 👩‍💻 devx

#5514 docs: updates big value docs
  docs/docs/guides/assets/big-value-chart.png
  docs/docs/guides/visualizing-your-results.mdx
Labels: 📖 documentation

#5523 docs: adds scheduled deliveries overview docs
  docs/docs/guides/assets/scheduled-deliveries-overview.jpg
  docs/docs/guides/how-to-create-scheduled-deliveries.mdx
Labels: 📖 documentation

#5553 docs: adds validator docs
  docs/docs/guides/assets/validate-dashboard.jpg
  docs/docs/guides/how-to-create-multiple-projects.md
  docs/docs/guides/table-calculations/adding-table-calculations.mdx
  docs/docs/guides/validating-your-content.mdx
  docs/sidebars.js
Labels: 📖 documentation

#5557 docs: updates roles doc to include admin access
  docs/docs/references/roles.mdx
Labels: 📖 documentation

#5580 fix: get space summary sql to exclude null values from access array
  packages/backend/src/models/SpaceModel.ts
Labels: 🐛 bug, ⚙️ backend

#5598 fix: Improve copy project types and remove undefined db fields
  packages/backend/src/database/entities/dashboards.ts
  packages/backend/src/database/entities/savedCharts.ts
  packages/backend/src/database/entities/spaces.ts
  packages/backend/src/models/ProjectModel/ProjectModel.ts
Labels: 🐛 bug, ⚙️ backend

#5604 fix: distinct on validation error
  packages/backend/src/models/ValidationModel/ValidationModel.ts
Labels: 🐛 bug, ⚙️ backend

#5641 docs: updates table viz docs with new config
  docs/docs/guides/assets/bar-chart.png
  docs/docs/guides/assets/chart-types.jpg
  docs/docs/guides/assets/chart-types.png
  docs/docs/guides/assets/columns-rows-metrics-example.jpg
  docs/docs/guides/assets/config-button.jpg
  docs/docs/guides/assets/config-button.png
  docs/docs/guides/assets/metrics-as-rows.jpg
  docs/docs/guides/assets/pivot-table-config.jpg
  docs/docs/guides/assets/pivoted-table.jpg
  docs/docs/guides/assets/stacked-bar-chart.png
  docs/docs/guides/assets/table-chart.png
  docs/docs/guides/visualizing-your-results.mdx
Labels: 📖 documentation

#5650 style: Migrate Settings Bluprint Card to Mantine
  packages/e2e/cypress/e2e/settings/invites.cy.ts
  packages/frontend/src/components/DbtCloudSettings/index.tsx
  packages/frontend/src/components/ProjectAccess/ProjectAccess.styles.ts
  packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/ConnectManuallyStep1.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectManually/index.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectSuccess.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/ProjectConnectFlow.styles.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/SelectWarehouse.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnectFlow/UnsupportedWarehouse.tsx
  packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
  packages/frontend/src/components/ProjectConnection/index.tsx
  packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.styles.tsx
  packages/frontend/src/components/ProjectTablesConfiguration/ProjectTablesConfiguration.tsx
  packages/frontend/src/components/SettingsScheduledDeliveries/index.tsx
  packages/frontend/src/components/SettingsUsageAnalytics/SettingsUsageAnalytics.styles.ts
  packages/frontend/src/components/SettingsUsageAnalytics/index.tsx
  packages/frontend/src/components/SettingsValidator/index.tsx
  packages/frontend/src/components/UserSettings/InvitesPanel/index.tsx
  packages/frontend/src/components/UserSettings/ProjectManagementPanel/ProjectManagementPanel.styles.ts
  packages/frontend/src/components/UserSettings/ProjectManagementPanel/index.tsx
  packages/frontend/src/components/UserSettings/UserManagementPanel/UserManagementPanel.styles.ts
  packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
  packages/frontend/src/components/common/Settings/SettingsCard.tsx
  packages/frontend/src/pages/Settings.styles.tsx
  packages/frontend/src/pages/Settings.tsx
Labels: 🖥 frontend

#5665 fix: check copy project access
  packages/backend/src/services/ProjectService/ProjectService.ts
Labels: 🐛 bug, 🚨 P1

#5674 docs: add validate docs to sidebar
  docs/docs/guides/cli/assets/project-id.png
  docs/docs/guides/cli/how-to-use-lightdash-validate.mdx
  docs/docs/guides/validating-your-content.mdx
  docs/sidebars.js
Labels: 📖 documentation

#5677 fix: fixes typo in start-preview
  packages/cli/src/handlers/dbt/validate.ts
Labels: 🐛 bug

#5646 chore: clean projects in e2e tests
  packages/e2e/cypress/cli/cli.cy.ts
  packages/e2e/cypress/e2e/createProjects.cy.ts
  packages/e2e/cypress/support/commands.ts
Labels: 👩‍💻 devx

#5699 fix: virtual table with empty ref
  packages/frontend/package.json
  packages/frontend/src/components/common/PivotTable/index.tsx
  packages/frontend/src/components/common/Table/ScrollableTable/TableBody.tsx
  yarn.lock
Labels: 🐛 bug, 🖥 frontend
