Repository lightdash/lightdash, pull requests merged in 2023-04, with the labels that each got.

#5092 docs: update roles and permissions docs with scheduled deliveries
  docs/docs/references/roles.mdx
Labels: 📖 documentation

#5117 fix: redirect new user to first default project
  packages/frontend/src/pages/Projects.tsx
Labels: 🐛 bug

#5119 fix: add logger to `downloadCsv` job
  packages/backend/src/scheduler/SchedulerTask.ts
Labels: 🐛 bug

#5113 fix: disable browser retries
  packages/backend/src/clients/Slack/Slackbot.ts
  packages/backend/src/scheduler/SchedulerTask.ts
  packages/backend/src/services/UnfurlService/UnfurlService.ts
Labels: 🐛 bug

#5141 fix: handle error for multiple orgs registration when it's not allowed
  packages/backend/src/controllers/userController.ts
  packages/backend/src/generated/routes.ts
  packages/backend/src/services/UserService.ts
  packages/frontend/src/hooks/user/useUserDeleteMutation.ts
  packages/frontend/src/pages/JoinOrganization.tsx
Labels: 🐛 bug

#5142 chore: rename organisation hooks to american-english spelling
  packages/frontend/src/components/AppRoute.tsx
  packages/frontend/src/components/ChartConfigPanel/Series/SeriesColorPicker.tsx
  packages/frontend/src/components/ChartConfigPanel/Series/index.tsx
  packages/frontend/src/components/UserSettings/AllowedDomainsPanel/index.tsx
  packages/frontend/src/components/UserSettings/AppearancePanel/index.tsx
  packages/frontend/src/components/UserSettings/DeleteOrganisationPanel/index.tsx
  packages/frontend/src/components/UserSettings/OrganisationPanel/index.tsx
  packages/frontend/src/components/common/modal/OrganisationDeleteModal.tsx
  packages/frontend/src/hooks/echarts/useEcharts.ts
  packages/frontend/src/hooks/organization/useAllowedDomains.ts
  packages/frontend/src/hooks/organization/useOrganization.ts
  packages/frontend/src/hooks/organization/useOrganizationCreateMutation.ts
  packages/frontend/src/hooks/organization/useOrganizationDeleteMultation.ts
  packages/frontend/src/hooks/organization/useOrganizationUpdateMutation.ts
  packages/frontend/src/pages/CreateProject.tsx
  packages/frontend/src/pages/Invite.tsx
  packages/frontend/src/pages/JoinOrganization.tsx
  packages/frontend/src/pages/Settings.tsx
Labels: tech-debt

#5144 chore: rename useDeleteUserMutation hook to useDeleteOrganizationUserMutation
  packages/frontend/src/components/UserSettings/UserManagementPanel/index.tsx
  packages/frontend/src/hooks/useOrganizationUsers.ts
Labels: tech-debt

#5146 chore: rename other delete mutation hooks
  packages/frontend/src/components/common/SpaceActionModal/index.tsx
  packages/frontend/src/components/common/modal/ChartDeleteModal.tsx
  packages/frontend/src/components/common/modal/DashboardDeleteModal.tsx
  packages/frontend/src/hooks/dashboard/useDashboard.tsx
  packages/frontend/src/hooks/useSavedQuery.ts
  packages/frontend/src/hooks/useSpaces.ts
  packages/frontend/src/pages/Dashboard.tsx
Labels: tech-debt

#5147 chore: rename organization spelling in backend
  packages/backend/src/analytics/LightdashAnalytics.ts
  packages/backend/src/database/migrations/20220125142122_add_organisation_allowed_domains_column.ts
  packages/backend/src/database/migrations/20230308100040_remove_org_allowed_email_domains.ts
  packages/backend/src/models/OrganizationModel.ts
  packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
  packages/backend/src/services/OrganizationService/OrganizationService.test.ts
  packages/backend/src/services/OrganizationService/OrganizationService.ts
Labels: tech-debt

#5150 feat: send slack message for empty csv results
  packages/backend/src/clients/Slack/SlackMessageBlocks.ts
  packages/backend/src/scheduler/SchedulerTask.ts
Labels: ✨ feature-request

#5151 chore: rename organization spelling in common package
  packages/backend/src/generated/routes.ts
  packages/backend/src/models/InviteLinkModel.ts
  packages/backend/src/models/OrganizationModel.ts
  packages/backend/src/services/OrganizationService/OrganizationService.mock.ts
  packages/backend/src/services/OrganizationService/OrganizationService.ts
  packages/common/src/index.ts
  packages/common/src/types/organization.ts
  packages/frontend/src/components/UserSettings/OrganizationPanel/index.tsx
  packages/frontend/src/hooks/organization/useOrganization.ts
Labels: tech-debt

#5181 chore: reuse env vars in docker-compose.dev.yml containers
  docker/docker-compose.dev.yml
Labels: 🐛 bug

#5187 chore: extract routes
  packages/frontend/src/App.tsx
  packages/frontend/src/Routes.tsx
  packages/frontend/src/pages/Dashboard.tsx
  packages/frontend/src/pages/JoinOrganization.tsx
  packages/frontend/src/pages/Projects.tsx
  packages/frontend/src/pages/VerifyEmail.tsx
Labels: 👩‍💻 devx

#5174 fix: e2e test with sql runner and csv download
  packages/e2e/cypress/e2e/downloadCsv.cy.ts
Labels: 👩‍💻 devx
