Repository lightdash/lightdash, pull requests merged in 2023-09, with the labels that each got.

#6979 docs: updates filters docs for non-aggregate metrics
  docs/docs/references/metrics.mdx
Labels: 📖 documentation

#7004 feat: show MetricFlow SQL
  packages/frontend/package.json
  packages/frontend/src/features/metricFlow/components/MetricFlowSqlCard.tsx
  packages/frontend/src/features/metricFlow/components/MetricFlowSqlCode.tsx
  packages/frontend/src/pages/MetricFlow.tsx
  yarn.lock
Labels: ✨ feature-request

#7002 refactor: handle google auth and access token in useGDriveAccessToken hook
  packages/frontend/src/components/Explorer/ExportGsheets/index.tsx
  packages/frontend/src/features/sync/components/SelectGoogleSheetButton.tsx
  packages/frontend/src/hooks/gdrive/useGdrive.ts
Labels: tech-debt

#7003 refactor: move export google sheet export button to features
  packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
  packages/frontend/src/components/Explorer/ExportGsheets/index.tsx
  packages/frontend/src/components/ExportSelector/index.tsx
  packages/frontend/src/features/export/components/ExportToGoogleSheet.tsx
  packages/frontend/src/features/export/hooks/useExportToGoogleSheet.tsx
  packages/frontend/src/features/export/index.ts
Labels: tech-debt

#7029 chore: improve dev backend workflow with tsx
  package.json
  packages/backend/package.json
  yarn.lock
Labels: 👩‍💻 devx

#7128 docs: updates joins docs to include fields reference
  docs/docs/references/joins.md
Labels: 📖 documentation

#7141 docs: update metrics.mdx filters
  docs/docs/references/metrics.mdx
Labels: 📖 documentation

#7152 chore: trigger e2e tests based on changed files
  .github/file-filters.yml
  .github/workflows/cli-tests.yml
  .github/workflows/e2e-tests.yml
  packages/e2e/cypress/e2e/app/createProjects.cy.ts
  packages/e2e/cypress/e2e/app/dashboard.cy.ts
  packages/e2e/cypress/e2e/app/dates.cy.ts
  packages/e2e/cypress/e2e/app/downloadCsv.cy.ts
  packages/e2e/cypress/e2e/app/explore.cy.ts
  packages/e2e/cypress/e2e/app/formats.cy.ts
  packages/e2e/cypress/e2e/app/globalSearch.cy.ts
  packages/e2e/cypress/e2e/app/login.cy.ts
  packages/e2e/cypress/e2e/app/projectPermission.cy.ts
  packages/e2e/cypress/e2e/app/savedDashboards.cy.ts
  packages/e2e/cypress/e2e/app/settings/invites.cy.ts
  packages/e2e/cypress/e2e/app/settings/profile.cy.ts
  packages/e2e/cypress/e2e/app/sqlrunner.cy.ts
  packages/e2e/cypress/e2e/app/userAttributes.cy.ts
Labels: 👩‍💻 devx, ⚡️ LightSmash Day

#7187 docs: how to run headless browser locally
  .github/CONTRIBUTING.md
Labels: ⚡️ LightSmash Day

#7204 fix: disable move-to-space option for viewers
  packages/frontend/src/components/DashboardTiles/DashboardChartTile.tsx
Labels: 🐛 bug, 🖥 frontend

#7216 docs: Update metrics.mdx
  docs/docs/references/metrics.mdx
Labels: 📖 documentation

#7226 fix: remove limit and get all available filters per chart
  packages/backend/src/models/SavedChartModel.ts
Labels: 🐛 bug

#7252 docs: Update dimensions.mdx
  docs/docs/references/dimensions.mdx
Labels: 📖 documentation
