Repository lightdash/lightdash, pull requests merged in 2025-06, with the labels that each got.

#15241 fix: generate pivot fields for SQL query downloads
  packages/backend/src/services/AsyncQueryService/AsyncQueryService.ts
Labels: 🐛 bug

#15239 chore: add authentication tracking to project analytics
  packages/backend/src/analytics/LightdashAnalytics.ts
  packages/backend/src/services/ProjectService/ProjectService.ts
Labels: released

#15256 feat: Improve agent information on a new thread
  packages/frontend/src/components/FadeTransition.tsx
  packages/frontend/src/ee/features/aiCopilot/components/ChatElements/AgentChatInput.tsx
  packages/frontend/src/ee/pages/AiAgents/AgentPage.tsx
  packages/frontend/src/ee/pages/AiAgents/AgentThreadPage.tsx
  packages/frontend/src/ee/pages/AiAgents/AiAgentNewThreadPage.tsx
  packages/frontend/src/mantine8Theme.ts
Labels: released

#15235 chore: restructure ai agent service and decouple it from ai service
  packages/backend/src/ee/clients/OpenAi.ts
  packages/backend/src/ee/clients/Slack/SlackBot.ts
  packages/backend/src/ee/controllers/aiAgentController.ts
  packages/backend/src/ee/controllers/aiController.ts
  packages/backend/src/ee/index.ts
  packages/backend/src/ee/models/AiAgentModel.ts
  packages/backend/src/ee/models/CommercialCatalogModel.ts
  packages/backend/src/ee/models/CommercialSlackAuthenticationModel.ts
  packages/backend/src/ee/scheduler/SchedulerWorker.ts
  packages/backend/src/ee/services/AiAgentService.ts
  packages/backend/src/ee/services/AiService/AiService.ts
  packages/backend/src/ee/services/AiService/utils/aiCopilot/toolErrorWrapper.ts
  packages/backend/src/ee/services/AiService/utils/errors.ts
  packages/backend/src/ee/services/ai/agents/agent.ts
  packages/backend/src/ee/services/ai/embeds/embed.ts
  packages/backend/src/ee/services/ai/models/openai-gpt-4.1.ts
  packages/backend/src/ee/services/ai/models/openai-text-embedding-3-large.ts
  packages/backend/src/ee/services/ai/tools/generateBarVizConfig.ts
  packages/backend/src/ee/services/ai/tools/generateCsv.ts
  packages/backend/src/ee/services/ai/tools/generateQueryFilters.ts
  packages/backend/src/ee/services/ai/tools/generateTimeSeriesVizConfigTool.ts
  packages/backend/src/ee/services/ai/tools/getOneLineResult.ts
  packages/backend/src/ee/services/ai/types/followUpTools.ts
  packages/backend/src/ee/services/ai/utils/getSlackBlocks.ts
  packages/backend/src/ee/services/ai/utils/validators.ts
  packages/backend/src/ee/services/ai/visualizations/csvFile.ts
  packages/backend/src/ee/services/ai/visualizations/getPivotedResults.ts
  packages/backend/src/ee/services/ai/visualizations/renderEcharts.ts
  packages/backend/src/ee/services/ai/visualizations/timeSeriesChart.ts
  packages/backend/src/ee/services/ai/visualizations/types.ts
  packages/backend/src/ee/services/ai/visualizations/verticalBarChart.ts
  packages/backend/src/generated/routes.ts
  packages/backend/src/generated/swagger.json
  packages/backend/src/models/CatalogModel/CatalogModel.ts
  packages/backend/src/services/CatalogService/CatalogService.ts
  packages/common/src/ee/Ai/types.ts
  packages/common/src/types/errors.ts
  packages/frontend/src/ee/pages/AiConversations.tsx
Labels: released

#15244 feat: add OpenAI API key to config for AI Copilot
  packages/backend/src/config/parseConfig.ts
  packages/backend/src/ee/services/AiAgentService.ts
Labels: released

#15388 fix: wait for non-null charts' responses
  packages/backend/src/services/UnfurlService/UnfurlService.ts
Labels: 🐛 bug

#15397 fix: add null checks to apiError properties in ApiErrorDisplay
  packages/frontend/src/hooks/toaster/useToaster.tsx
Labels: released

#15433 feat: improve sql runner completion
  packages/frontend/src/features/sqlRunner/components/SqlEditor.tsx
  packages/frontend/src/features/sqlRunner/hooks/useDetectedTableFields.tsx
  packages/frontend/src/features/sqlRunner/hooks/useMultipleTableFields.tsx
  packages/frontend/src/features/sqlRunner/hooks/useTableFields.tsx
Labels: 🖥 frontend
