Repository lightdash/lightdash, pull requests merged in 2025-03, with the labels that each got.

#13918 chore: remove @types/snowflake-sdk
  packages/warehouses/package.json
  pnpm-lock.yaml
Labels: dependencies

#13937 chore: set correct sentry tags on saveScreenshot errors
  packages/backend/src/services/UnfurlService/UnfurlService.ts
  packages/common/src/types/errors.ts
Labels: 👩‍💻 devx

#14030 chore: set warehouse type tag for Sentry
  packages/backend/src/services/ProjectService/ProjectService.ts
Labels: 👩‍💻 devx

#14080 chore: categorize not-implemented-errors
  packages/common/src/utils/conditionalFormatting.ts
  packages/frontend/src/components/common/Filters/utils/getPlaceholderByFilterTypeAndOperator.ts
Labels: 👩‍💻 devx

#14103 chore: add cursor rules for FE and BE
  .cursor/rules/backend.mdc
  .cursor/rules/frontend.mdc
Labels: 👩‍💻 devx

#14136 chore: increase playwright response wait timeout to 90000
  packages/backend/src/services/UnfurlService/UnfurlService.ts
Labels: 💜 customer support

#14150 fix: User completion modal blocking people from completing sign up
  packages/frontend/src/components/UserCompletionModal/UserCompletionModal.tsx
Labels: 🐛 bug, 💜 customer support

#14170 fix: infinite loop error on pivotted charts
  packages/frontend/src/components/Explorer/CustomMetricModal/hooks/useDataForFiltersProvider.ts
  packages/frontend/src/components/Explorer/FiltersCard/FiltersCard.tsx
  packages/frontend/src/components/Explorer/ResultsCard/ExplorerResults.tsx
  packages/frontend/src/components/Explorer/ResultsCard/ResultsCard.tsx
  packages/frontend/src/components/Explorer/VisualizationCard/VisualizationCard.tsx
  packages/frontend/src/hooks/useQueryResults.ts
  packages/frontend/src/pages/MinimalSavedExplorer.tsx
Labels: 🐛 bug, 🖥 frontend
